export const symptoms = [
  { type: "common", name: "headache" },
  { type: "common", name: "nausea" },
  { type: "common", name: "stuffy nose" },
  { type: "common", name: "sore throat" },
  { type: "common", name: "dizziness" },
  { type: "common", name: "toothache" },
  { type: "dangerous", name: "high temperature" },
  { type: "dangerous", name: "vomit" },
  { type: "dangerous", name: "difficulty breathing" },
  { type: "dangerous", name: "acute diarrhea" },
  { type: "dangerous", name: "acute heart pain" },
  { type: "dangerous", name: "migraine" },
  { type: "critical", name: "internal bleeding" },
  { type: "critical", name: "fracture" },
  { type: "critical", name: "open fracture" },
  { type: "critical", name: "acute abdominal pain" },
  { type: "critical", name: "loss of taste and smell" },
  { type: "critical", name: "strong fluctuations in blood pressure" },
];
